<a href="https://colab.research.google.com/github/adithya1010/Naan-Mudhalvan-Labs/blob/main/Task-3/NaanMudhalvan_Task3_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task-3-Iris Species Classification




Project done with inputs from Gemini 1.5 Flash

**Link to Chat:** https://www.getmerlin.in/share/chat/PLYL-ATb72f

**References:**
1. https://www.youtube.com/watch?v=rF4m6g46p-g
2. https://medium.com/@myselfaman12345/c-and-gamma-in-svm-e6cee48626be
3.https://www.analyticsvidhya.com/blog/2021/06/tune-hyperparameters-with-gridsearchcv/


### Importing libraries

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

###Loading the dataset

In [ ]:
# Load the iris dataset
iris = datasets.load_iris()
X = iris.data[:, 2:]  # We'll only use petal length and width for simplicity
y = iris.target


### Splitting data into training and testing data

In [ ]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

A regularization parameter is a number that controls the trade-off between fitting data and incorporating prior information in a model. It's a key element of machine learning that helps prevent overfitting

Radial basis function video explanation:
https://www.youtube.com/watch?v=rF4m6g46p-g

C and Gamma Explanation: https://medium.com/@myselfaman12345/c-and-gamma-in-svm-e6cee48626be

In [ ]:
param_grid = {'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001], 'kernel': ['rbf']}



**Support Vector Machine (SVM):**

A Support Vector Machine (SVM) is a supervised learning algorithm used for classification and regression tasks. It works by finding the hyperplane that maximally separates the classes in the feature space. SVMs are effective in high-dimensional spaces and can handle non-linearly separable data by using kernels. The algorithm identifies the support vectors, which are the data points closest to the hyperplane, and uses them to define the decision boundary. SVMs are widely used in various applications, including image classification, natural language processing, and bioinformatics. They are known for their high accuracy and robustness.

In [ ]:
# Create an SVM classifier
svm = SVC()

### Performing GridSearchCV

**GridSearchCV:** GridSearchCV acts as a valuable tool for identifying the optimal parameters for a machine learning model. Imagine you have a machine learning model with adjustable settings, known as hyperparameters, that can enhance its performance. GridSearchCV aids in pinpointing the best combination of these hyperparameters automatically.

**Here's a breakdown of the parameters you've specified:**

model: the machine learning model you want to tune.
param_grid: a dictionary containing the hyperparameters you want to tune, along with their respective ranges or values.
refit=True: refit the model with the best parameters on the entire dataset after tuning.
verbose=4: specify the verbosity level (4 means more detailed output).
n_jobs=-1: use all available CPU cores for parallel processing.
**Reference:**

https://www.analyticsvidhya.com/blog/2021/06/tune-hyperparameters-with-gridsearchcv/

In [ ]:
# Perform GridSearchCV to find the best hyperparameters
grid = GridSearchCV(svm, param_grid, refit=True, verbose=4)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.905 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.905 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.952 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.905 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.857 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.952 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.333 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf']},
             verbose=4)

Fitting 5 folds for each of 16 candidates involves a process called k-fold cross-validation. This technique is used to evaluate the performance of a model by dividing the available data into k subsets or folds. In this case, k is set to 5, meaning the data is split into 5 equal parts, and the model is trained and tested 5 times, each time using a different fold as the test set. This process is repeated for each of the 16 candidates, resulting in a total of 80 model fits. This approach helps to prevent overfitting and provides a more accurate estimate of the model's performance.

### Printing the best hyperparameters and score

In [ ]:
# Print the best hyperparameters and score
print("Best Hyperparameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Hyperparameters: {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}
Best Score: 0.9619047619047618


### Making predictions on the test set

In [ ]:
# Make predictions on the test set
grid_predictions = grid.predict(X_test)

### Evaluating the model

**Reference for Evaluation:** https://colab.research.google.com/drive/1-iwuPisFFoKaJJvfM6l71pmcMHMdU_cz

In [ ]:
# Evaluate the model
print(classification_report(y_test, grid_predictions))
print(confusion_matrix(y_test, grid_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
